-- MySQL Script generated by MySQL Workbench
-- Tue May 15 09:51:09 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema kamille
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kamille
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kamille` DEFAULT CHARACTER SET utf8 ;
USE `kamille` ;

-- -----------------------------------------------------
-- Table `kamille`.`ap_variables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ap_variables` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `value` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
